<?php

namespace Database\Seeders;

use App\Models\Company;
use App\Models\LeadSource;
use Illuminate\Database\Seeder;

class DevLeadSourceSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Get the first test Company generated by CompanySeeder
        $company = Company::first();

        if (! $company) {
            return;
        }

        $devSources = [
            'Feira de Negócios SP',
            'Parceria Agência K',
            'Outdoor Avenida Principal',
            'Panfleto Bairro X',
        ];

        foreach ($devSources as $sourceName) {
            LeadSource::firstOrCreate(
                ['name' => $sourceName, 'company_id' => $company->id]
            );
        }
    }
}
